import "oaidl.idl";
import "ocidl.idl";

[
	uuid(2b68b4d0-a756-41c9-9c75-910d8d0e5457),
	version(0.1),
	endpoint("ncalrpc:[WpRootRpc]") 
]
interface WpRootRpc
{
	int RpcTestIncrement([in] int val);

	//void* RpcCreateFile(
	//	[in, string] wchar_t *filepath,
	//	[in] unsigned long access,
	//	[in] unsigned long share,
	//	/*void *security, */
	//	[in] unsigned long creation,
	//	[in] unsigned long flags/*, void *template*/);
}